
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: binance-bot_development

test:
  <<: *default
  database: binance-bot_test

production:
  <<: *default
  database: binance-bot_production
  username: binance-bot
  password: <%= ENV['BINANCE-BOT_DATABASE_PASSWORD'] %>
